version: '3.9'

volumes:
   geoserver-data:
      driver_opts:
        type: cifs
        o: "username=geoserver,password=nas123456,vers=2.0,file_mode=0777,dir_mode=0777"
        device: "192.168.31.88/geoservernas/data_dir"
services:
   geoserver:
      image: puhou/gs:1.0
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_ADMIN_USER=admin
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
