version: '3'

volumes:
   geoserver-data:
      geoserver-cluster-data:
      driver_opts:
        type: cifs
        o: "username=geoserver,password=nas123456,vers=2.0,file_mode=0777,dir_mode=0777"
        device: "//192.168.31.88/geoservernas/data_dir"
services:

   geoserver:
      image:  puhou/gs:1.0 
      build:
        context: .
        args:
          IMAGE_VERSION: ${IMAGE_VERSION}
          JAVA_HOME: ${JAVA_HOME}
          GS_VERSION: ${GS_VERSION}
          WAR_URL: ${WAR_URL}
          DOWNLOAD_ALL_STABLE_EXTENSIONS: ${DOWNLOAD_ALL_STABLE_EXTENSIONS}
          DOWNLOAD_ALL_COMMUNITY_EXTENSIONS: ${DOWNLOAD_ALL_COMMUNITY_EXTENSIONS}
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - RECREATE_DATADIR=${RECREATE_DATADIR}
        - HTTP_PROXY_NAME
        - HTTP_PROXY_PORT

