version: '3.9'

volumes:
   geoserver-data:
services:
   geoserver:
      image: puhou/gs:1.
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      restart: on-failure
      environment:
        - GEOSERVER_ADMIN_USER=admin
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   nginx:
     image: nginx
     volumes:
       - ./sites-enabled:/etc/nginx/conf.d:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     depends_on:
       - geoserver
     ports:
       - "80:80"